/*
 * TIMER_Config.h
 *
 *  Created on: Dec 26, 2023
 *      Author: Nada Mamdouh
 */

#ifndef MCAL_TIMER_TIMER_CONFIG_H_
#define MCAL_TIMER_TIMER_CONFIG_H_

#define FREQUENCY          16000000             // HSI 16 clk

typedef struct{
	u8 Channel_NO;
	u8 Edge_polarity;
	u8 IC_Prescaler;
	u16 Filter;
}TIMx_IC_Cfg_t;

typedef struct{
	u32 DutyCycle;
	u32 Period;
	u32 Time_OnPeriod;                // time between rising and falling edges "High pulse"
}MeasurePWM_t;

typedef struct{
	u8 Mode;
	u8 Channel_NO;
	u8 Polarity;
}TIMx_PWM_Cfg_t;

typedef struct{
	u16 prescaler;
	u8 auto_reload_EN;               // enable or disable auto-reload
	u8 Count_Direction;              // counting up or down
}TIMx_Counter_Cfg_t;

/* ------- Channel NO ------- */
#define TIMER_CHANNEL_1        0
#define TIMER_CHANNEL_2        2
#define TIMER_CHANNEL_3        4
#define TIMER_CHANNEL_4        6

/* --------- PWM MODE --------- */
#define PWM_MODE_1             0
#define PWM_MODE_2             1

/* --------- PWM POLARITY --------- */
#define PWM_POLARITY_HIGH      0
#define PWM_POLARITY_LOW       1

/* ------- Edge Polarity ------- */
#define TIMER_EDGE_RISING      0
#define TIMER_EDGE_FALLING     1
#define TIMER_EDGE_BOTH        2

/* ------ Counting Direction ------ */
#define  TIMER_COUNT_UP        0
#define  TIMER_COUNT_DOWN      1

/* --------- Auto-reload --------- */
#define TIMER_AUTORELOAD_ENABLE   1
#define TIMER_AUTORELOAD_DISABLE  0

/* ----------- IC_Filter ------------ */
/*Explanation:
 * FCK : sampling frequency equals clock frequency
 * FDTS_x: sampling frequency equals to FDTS/x (digital timebase signal -> clock signal generated by internal peripherals such as timers)
 * Nx  : N consecutive events are needed to validate a transition on the output
 * */
#define TIMER_IC_FILTER_FDTS_NONE      0b0000
#define TIMER_IC_FILTER_FCK_N2         0b0001
#define TIMER_IC_FILTER_FCK_N4         0b0010
#define TIMER_IC_FILTER_FCK_N8         0b0011
#define TIMER_IC_FILTER_FDTS_2_N6      0b0100
#define TIMER_IC_FILTER_FDTS_2_N8      0b0101
#define TIMER_IC_FILTER_FDTS_4_N6      0b0110
#define TIMER_IC_FILTER_FDTS_4_N8      0b0111
#define TIMER_IC_FILTER_FDTS_8_N6      0b1000
#define TIMER_IC_FILTER_FDTS_8_N8      0b1001
#define TIMER_IC_FILTER_FDTS_16_N5     0b1010
#define TIMER_IC_FILTER_FDTS_16_N6     0b1011
#define TIMER_IC_FILTER_FDTS_16_N8     0b1100
#define TIMER_IC_FILTER_FDTS_32_N5     0b1101
#define TIMER_IC_FILTER_FDTS_32_N6     0b1110
#define TIMER_IC_FILTER_FDTS_32_N8     0b1111

/* ----------- IC_Prescaler ------------ */
/* PRESCALER_x: capture is done once every x events */
#define TIMER_IC_PRESCALER_NO         0b00
#define TIMER_IC_PRESCALER_2          0b01
#define TIMER_IC_PRESCALER_4          0b10
#define TIMER_IC_PRESCALER_8          0b11


#endif /* MCAL_TIMER_TIMER_CONFIG_H_ */
